% autoexec_cfg generated by Configure AFC. Add your local preferences here.

def.externSoundCommand = '';
def.internSoundCommand = 'audioplayer';
def.markIntervalDelay = 0.2;                    % tweak if audioplayer is used (adds delay to sound to synchronize with visual feedback)
def.language = 'EN';
